# Week1

## 倒包

In [2]:
import pandas as pd

## 读取Excel文件

In [3]:
df = pd.read_excel("./数据分析测试题.xlsx")
df

,专业,题型,难度,对应知识点,题干,选项（如果有）,答案
0,数据分析,单选,1,数据分析概念,关于电商网站数据抓取的方式不包括,A.第三方工具抓取\nB.爬虫程序抓取\nC.数据库提取\nD.人工抓取,C
1,数据分析,判断题,1,数据分析概念,以下软件/语言是否都属于数据分析软件/语言,A.SPSS\nB.Python\nC.Excel\nD.R,是
2,数据分析,单选,1,数据分析概念,在电商中针对仓储备货场景一般采用什么分析方式,A.线性回归\nB.数学仿真\nC.逻辑回归\nD.分类,B
3,数据分析,填空题,2,数据分析概念,数据分析的四大步骤是什么,NaN,数据抓取→数据清洗→数据分析→业务决策
4,数据分析,填空题,2,数据分析概念,优秀数据分析师的三个特点是什么,NaN,业务理解、工具使用、沟通表达
5,数据分析,单选,1,数据分析概念,Excel相比于Python的优势是什么,A.处理大数据分析时效率较高\nB.分析工具学习入门门槛低\nC.数据可视化个性度高,B
6,数据分析,多选,1,数据分析概念,Excel适用于哪些类似的公司进行数据分析,A.电商入驻商\nB.电商平台\nC.线下零售商\nD.电商服务商,A、C
7,数据分析,多选,2,数据分析概念,数据分析报告对一线业务的帮助包含,A.广告投放优化\nB.渠道管理优化\nC.人员管理优化\nD.用户管理优化,A、B、C、D
8,数据分析,填空题,3,数据分析概念,数据分析报告的要求包含哪些,NaN,A.简洁性\nB.概括性\nC.方向性
9,数据分析,填空题,3,数据分析概念,互联网数据分析师需要对什么指标负责,NaN,数据分析结果的准确性和价值度
10,数据分析,填空题,3,数据分析概念,互联网数据分析师与运营对数据负责点的区别是什么,NaN,运营对数据的涨跌负责，数据分析师对数据分析结果的准确性和价值度负责
11,数据分析,填空题,3,数据分析概念,互联网产品经理与数据分析师对数据负责点的区别是什么,NaN,产品经理对产品功能使用数据的涨跌负责，数据分析师对数据分析结果的准确性和价值度负责
12,数据分析,单选,2,数据分析概念,在电商中针对业绩预测场景一般采用什么分析方式,A.线性回归\nB.数学仿真\nC.逻辑回归\nD.分类,A
13,数据分析,单选,3,数据分析概念,在互联网中针对用户性别的预测一般采用什么分析方式,A.线性回归\nB.数学仿真\nC.逻辑回归\nD.分类,C
14,数据分析,单选,3,数据分析概念,在电商中针对商品区分场景一般采用什么分析方式,A.线性回归\nB.数学仿真\nC.逻辑回归\nD.分类,D
15,数据分析,多选,1,数据分析概念,以下哪些属于描述性分析中涉及的分析方法,A.平均数\nB.分布\nC.相关性\nD.可视化图表,A、B、C、D
16,数据分析,判断题,1,数据分析概念,Excel软件无法实现数学仿真,NaN,错
17,数据分析,判断题,1,数据分析概念,Excel软件无法实现逻辑回归,NaN,错
18,数据分析,单选题,2,数据分析概念,适合观察时间序列的数据可视化图表是什么,A.柱状图\nB.折线图\nC.雷达图\nD.散点图,B
19,数据分析,单选题,2,数据分析概念,适合比较数据大小的数据可视化图表是什么,A.柱状图\nB.折线图\nC.雷达图\nD.散点图,A
20,数据分析,单选题,2,数据分析概念,适合观察多指标关系的数据可视化图表是什么,A.柱状图\nB.折线图\nC.雷达图\nD.散点图,D
21,数据分析,填空题,3,数据分析概念,散点图如果想在图表中增加数据维度需要使用哪种数据可视化图表,NaN,气泡图
22,数据分析,填空题,3,数据分析概念,Excel中的气泡图在不使用VBA语言的情况下最多可以展现多少个维度的数据,NaN,4
23,数据分析,单选题,2,数据分析概念,适合观察转化流失的数据可视化图表是什么,A.柱状图\nB.漏斗图\nC.雷达图\nD.散点图,B
24,数据分析,单选题,2,数据分析概念,以下类型公司中数据分析需求最大的是,A.电商入驻商\nB.电商平台\nC.线下零售商\nD.电商服务商,B
25,数据分析,单选题,1,Pandas数据处理,使用Pandas读取Excel数据时，用哪个参数可以指定读取其他sheet页的内容？,A.sheet\nB.sheet_name\nC.sheet_page\nD.sheet_n...,B
26,数据分析,单选题,1,NumPy数据运算,声明一个NumPy列表，下列哪项代码是正确的？,"A.np.array(1,2,3,4)\nB.np.array(1,2,(3,4))\nC....",C
27,数据分析,单选题,1,NumPy数据运算,"关于代码：np.arange( 10, 30, 5 )下列描述错误的是？",A.第一个参数代表获取结果列表开始的数字\nB.第二个参数代表获取结果列表结束的数字\nC....,D
28,数据分析,填空题,1,Pandas数据处理,有DataFrame数据类型变量data，我们可以使用_________方法查看数据详情？,NaN,info()
29,数据分析,单选题,1,Pandas数据处理,DataFrame数据类型的方法中，哪个函数可以实现删除掉空数据,A.fillna\nB.dropna\nC.deletena\nD.clearna,B
30,数据分析,单选题,1,Pandas数据处理,DataFrame数据类型的方法中，哪个函数可以实现空数据的填充,A.fillna\nB.dropna\nC.deletena\nD.clearna,A
31,数据分析,判断题,1,Matplotlib数据可视化,在使用Matplotlib的pie函数进行饼图绘制时，我们需要提前算好各分类的比例后，再放入...,A.对\nB.错,A
32,数据分析,判断题,2,Matplotlib数据可视化,在使用Matplotlib的pie函数进行饼图绘制时，__________参数代表饼图中各数...,NaN,labels
33,数据分析,填空题,1,Matplotlib数据可视化,在使用Matplotlib进行图形绘制时，______函数可以设置x轴的标签文本,NaN,xlabel
34,数据分析,填空题,1,Matplotlib数据可视化,在使用Matplotlib进行图形绘制时，______函数可以设置y轴的标签文本,NaN,ylabel
35,数据分析,填空题,1,Matplotlib数据可视化,在使用Matplotlib进行图形绘制时，______函数可以设置图形内容的标题,NaN,title
36,数据分析,填空题,2,Matplotlib数据可视化,在使用Matplotlib进行图形绘制时，______函数可以设置文本标签的图例,NaN,legend
37,数据分析,判断题,1,Matplotlib数据可视化,在引用Matplotlib时，我们会这样写代码import matplotlib.pyplo...,A.对\nB.错,B
38,数据分析,判断题,1,Matplotlib数据可视化,我们在使用Matplotlib绘制柱状图时，有时会修改图形的颜色，我们对color参数进行赋...,A.对\nB.错,A
39,数据分析,判断题,1,Matplotlib数据可视化,我们在使用Matplotlib绘制柱状图时，有一个参数可以设置柱体对齐的方式，这个参数是align,A.对\nB.错,A
40,数据分析,判断题,1,Matplotlib数据可视化,我们在使用Matplotlib绘制柱状图时，有一个参数可以设置刻度标签值，这个参数是tick...,A.对\nB.错,A
41,数据分析,判断题,1,Pandas数据处理,使用Pandas进行数据处理时，drop函数可以实现删除重复数据,A.对\nB.错,B
42,数据分析,判断题,1,Pandas数据处理,"DataFrame数据类型进行多条件数据筛选的时候，可以实现""与""运算的运算符是and",A.对\nB.错,B
43,数据分析,判断题,1,Pandas数据处理,"DataFrame数据类型进行多条件数据筛选的时候，可以实现""或""运算的运算符是or",A.对\nB.错,B
44,数据分析,判断题,1,Pandas数据处理,DataFrame数据类型，在处理空数据的时候，可以使用fillna方法进行空值填充,A.对\nB.错,A
45,数据分析,判断题,1,NumPy数据运算,Series数据类型声明时，我们想要自定义其索引的值，可以对index参数进行设置，就可以实...,A.对\nB.错,A
46,数据分析,判断题,1,NumPy数据运算,Pandas用Null来标记缺失数据,A.对\nB.错,B
47,数据分析,判断题,1,NumPy数据运算,在使用NumPy进行数据运算时，我们可以使用sqrt函数来直接计算元素的算数平方根,A.对\nB.错,A
48,数据分析,判断题,1,NumPy数据运算,"有NumPy对象arr，代码power(arr,4)k可以实现计算arr中各元素的4次方",A.对\nB.错,A
49,数据分析,判断题,1,NumPy数据运算,有NumPy对象arr，代码np.log(arr)可以实现计算arr中各元素以2为底的对数,A.对\nB.错,B

## 绝对路径和相对路径
- ../2.xlsx 上两级
- ../a/2.xlsx

In [4]:
df = pd.read_excel("./数据分析测试题.xlsx",sheet_name = "第一阶段第二套")

## 创建新df

In [5]:
df1 = pd.DataFrame({"aa":[1,2,3],
                       "bbb":[4,5,6]})
df1

   aa  bbb
0   1    4
1   2    5
2   3    6

In [6]:
df2 = pd.DataFrame({"aa":[1,2,3],
                       "bbb":[4,5,6]},
                  index = [101,102,103])
df2

     aa  bbb
101   1    4
102   2    5
103   3    6

## 查看长宽

In [7]:
df.shape

(50, 7)

In [8]:
(type(df.shape))

tuple

In [9]:
df.dtypes

专业         object
题型         object
难度          int64
对应知识点      object
题干         object
选项（如果有）    object
答案         object
dtype: object

In [10]:
df.index

RangeIndex(start=0, stop=50, step=1)

In [11]:
df2.index

Int64Index([101, 102, 103], dtype='int64')

In [12]:
df.columns

Index(['专业', '题型', '难度', '对应知识点', '题干', '选项（如果有）', '答案'], dtype='object')

In [13]:
df.values

array([['数据分析', '填空题', 1, '数据分析概念', '互联网营销活动数据分析的基本模型是什么', nan,
        '找出问题→分析问题→解决问题'],
       ['数据分析', '填空题', 2, '数据分析概念', '对于多维度数据之间相关性判断一般使用哪种分析模型？', nan,
        '波士顿矩阵'],
       ['数据分析', '多选', 2, '数据分析概念', '使用数学仿真时需要包含哪些元素',
        'A.平均数\nB.分布\nC.方差\nD.可视化图表', 'A、B、C、D'],
       ['数据分析', '判断题', 3, '数据分析概念', '数学仿真可以直接给出业务决策最优解', nan,
        '错（仿真值只是参考）'],
       ['数据分析', '多选', 3, '数据分析概念', '多变量线性回归时确定重要变量的方法包含',
        'A.向前选择\nB.向后选择\nC.混合选择', 'A、B、C'],
       ['数据分析', '判断题', 1, '数据分析概念', '回归中R^2的含义是Y中出现的变化可以被X解释的的比例', nan,
        '对'],
       ['数据分析', '判断题', 3, '数据分析概念', '多变量回归时，F统计量接近于1则一定说明自变量与因变量之间没有关系',
        nan, '错（还需要参考样本量）'],
       ['数据分析', '填空题', 3, '数据分析概念', '在市场营销中，通常对变量进行哪种变化来进行回归分析', nan,
        'ln函数'],
       ['数据分析', '单选', 3, '数据分析概念', '使用ln函数后，以下哪种回归分析可以进行',
        'A.商品排名→商品销量\nB.评价数量→商品销量\nC.评价等级→商品销量', nan],
       ['数据分析', '判断题', 1, '数据分析概念', '线性回归中t统计量可以用于计算自变量与因变量之间是否存在关系',
        nan, '对'],
       ['数据分析', '填空题', 2, '数据分析概念', '不能直接用线性回归来预测用户购买概率的原因为', nan,
        '线性回归会使概率值大于1'],
       ['数据分析', '填空题', 1, '数据分析概念', '在Excel的折线图中，如何快速将线性回归可视化', nan,
        '添加“趋势线”'],
       ['数据分析', '填空题', 3, '数据分析概念', '是哪两个因素导致了预测值与真实值之间的差异', nan,
        '模型的偏差与数据的误差'],
       ['数据分析', '多选', 1, '数据分析概念', '以下哪些图表为Excel中常用的图表类型',
        'A.折线图\nB.柱状图\nC.散点图\nD.雷达图', 'A、B、C、D'],
       ['数据分析', '判断题', 1, '数据分析概念', 'Excel2016版本可以直接生成漏斗图', nan, '错'],
       ['数据分析', '填空题', 2, '数据分析概念', '漏斗图在电商业务中最常用的分析场景是', nan, '广告投放分析'],
       ['数据分析', '填空题', 3, '数据分析概念',
        '如果要对一个电商品牌的多个入驻商店铺进行定位分析，Excel表中哪种图表最适合？', nan, '气泡图/散点图'],
       ['数据分析', '多选题', 2, '数据分析概念', '市场分析领域对于市场的划分包含以下哪些概念',
        'A.头部市场\nB.腰部市场\nC.长尾市场', nan],
       ['数据分析', '填空题', 3, '数据分析概念', '长尾市场和非长尾市场的核心区别在哪个指标', nan, '行业集中度'],
       ['数据分析', '填空题', 3, '数据分析概念', '蒙特卡罗模拟的数学本质是什么', nan, '概率'],
       ['数据分析', '填空题', 2, '数据分析概念', '在图表可视化中，需要用什么颜色来强调重点', nan, '红色'],
       ['数据分析', '多选', 1, '数据分析概念', '以下哪些软件/语言可完成数学仿真',
        'A.Excel\nB.Python\nC.Matlab\nD.Netlogo', 'A、B、C、D'],
       ['数据分析', '多选', 1, '数据分析概念', '在分析数据波动时常用的指标包含',
        'A.同比\nB.环比\nC.平均数\nD.标准差', 'A、B'],
       ['数据分析', '填空题', 3, '数据分析概念', '在分类问题下最常用的算法是', nan, 'K近邻回归'],
       ['数据分析', '判断题', 3, '数据分析概念', '互联网广告业务的数据分析流程与用户相关数据的分析流程相同', nan,
        '错（广告业务数据需要单独分析恶意点击数据）'],
       ['数据分析', '填空题', 1, 'Pandas数据处理',
        '使用Pandas读取Excel数据时，用__________参数可以指定读取其他sheet页的内容', nan,
        'sheet_name'],
       ['数据分析', '判断题', 1, 'NumPy数据运算',
        '声明一个NumPy列表时，我们可以直接把列表类型当做NumPy声明时初始化的参数，就像这样：\nimport numpy as np\nl = [1,2,3,4]\nn = np.array(l)',
        'A.对\nB.错\n', 'A'],
       ['数据分析', '单选题', 1, 'NumPy数据运算', '关于numpy的arange( )函数，下列描述错误的是？',
        'A.第一个参数代表获取结果列表开始的数字\nB.第二个参数代表获取结果列表结束的数字\nC.第三个参数代表获取结果列表数字与数字之间的间隔\nD.运行的结果不包含第一个参数中的数字',
        'D'],
       ['数据分析', '单选题', 1, 'Pandas数据处理',
        '有DataFrame数据类型变量data，我们可以使用什么方法查看数据详情？',
        'A.info()\nB.describe()\nC.description()\nD.details()', 'A'],
       ['数据分析', '判断题', 1, 'Pandas数据处理',
        'DataFrame数据类型的方法中，fillna函数可以实现删除掉空数据', 'A.对\nB.错\n', 'B'],
       ['数据分析', '判断题', 1, 'Pandas数据处理',
        'DataFrame数据类型的方法中，dropna函数可以实现空数据的填充', 'A.对\nB.错\n', 'B'],
       ['数据分析', '填空题', 1, 'Matplotlib数据可视化',
        '在使用Matplotlib的pie函数进行饼图绘制时，我们需要提前算好各分类的比例后，再放入pie函数的第_____个参数上，比例就会被设置好。',
        nan, 1],
       ['数据分析', '单选题', 2, 'Matplotlib数据可视化',
        '在使用Matplotlib的pie函数进行饼图绘制时，下列哪个参数代表饼图中各数据的类别名称',
        'A. explode\nB. size\nC. type\nD.labels', 'D'],
       ['数据分析', '单选题', 1, 'Matplotlib数据可视化',
        '在使用Matplotlib进行图形绘制时，什么函数可以设置x轴的标签文本',
        'A.xlabel\nB.ylabel\nC.title\nD.legend', 'A'],
       ['数据分析', '单选题', 1, 'Matplotlib数据可视化',
        '在使用Matplotlib进行图形绘制时，什么函数可以设置y轴的标签文本',
        'A.xlabel\nB.ylabel\nC.title\nD.legend', 'B'],
       ['数据分析', '单选题', 1, 'Matplotlib数据可视化',
        '在使用Matplotlib进行图形绘制时，什么函数可以设置图形内容的标题',
        'A.xlabel\nB.ylabel\nC.title\nD.legend', 'C'],
       ['数据分析', '单选题', 2, 'Matplotlib数据可视化',
        '在使用Matplotlib进行图形绘制时，什么函数可以设置文本标签的图例',
        'A.xlabel\nB.ylabel\nC.title\nD.legend', 'D'],
       ['数据分析', '填空题', 1, 'Matplotlib数据可视化',
        '在引用Matplotlib时，我们会这样写代码import matplotlib.pyplot，导入后我们一般都会为它起一个别名，通常我们会把别名命名为________',
        nan, 'plt'],
       ['数据分析', '填空题', 1, 'Matplotlib数据可视化',
        '我们在使用Matplotlib绘制柱状图时，有时会修改图形的颜色，我们对________参数进行赋值，才会达到修改颜色的目的.',
        nan, 'color'],
       ['数据分析', '填空题', 1, 'Matplotlib数据可视化',
        '我们在使用Matplotlib绘制柱状图时，有一个参数可以设置柱体对齐的方式，这个参数是________', nan,
        'align'],
       ['数据分析', '填空题', 1, 'Matplotlib数据可视化',
        '我们在使用Matplotlib绘制柱状图时，有一个参数可以设置刻度标签值，这个参数是________', nan,
        'tick_label'],
       ['数据分析', '填空题', 1, 'Pandas数据处理',
        '使用Pandas进行数据处理时，___________函数可以实现删除重复数据', nan,
        'drop_duplicates'],
       ['数据分析', '填空题', 1, 'Pandas数据处理',
        'DataFrame数据类型进行多条件数据筛选的时候，可以实现"与"运算的运算符是_______', nan, '&'],
       ['数据分析', '填空题', 1, 'Pandas数据处理',
        'DataFrame数据类型进行多条件数据筛选的时候，可以实现"或"运算的运算符是_______', nan, '|'],
       ['数据分析', '填空题', 1, 'Pandas数据处理',
        'DataFrame数据类型，在处理空数据的时候，可以使用_______方法进行空值填充', nan, 'fillna'],
       ['数据分析', '填空题', 1, 'NumPy数据运算',
        'Series数据类型声明时，我们想要自定义其索引的值，可以对________参数进行设置，就可以实现自定义索引值', nan,
        'index'],
       ['数据分析', '填空题', 1, 'NumPy数据运算', 'Pandas用_______来标记缺失数据', nan, nan],
       ['数据分析', '填空题', 1, 'NumPy数据运算',
        '在使用NumPy进行数据运算时，我们可以使用________函数来直接计算元素的算数平方根', nan, 'sqrt'],
       ['数据分析', '编程题', 1, 'NumPy数据运算',
        '有NumPy对象arr，请书写代码实现计算arr中各元素的4次方', nan, 'power(arr,4)'],
       ['数据分析', '编程题', 1, 'NumPy数据运算',
        '有NumPy对象arr，请写代码实现计算arr中各元素以2为底的对数', nan, 'np.log2(arr)']],
      dtype=object)

In [14]:
type(df.values)

numpy.ndarray

In [15]:
df.size

350

## 数据获取

In [16]:
df.head()
# 默认前5个

,专业,题型,难度,对应知识点,题干,选项（如果有）,答案
0,数据分析,填空题,1,数据分析概念,互联网营销活动数据分析的基本模型是什么,NaN,找出问题→分析问题→解决问题
1,数据分析,填空题,2,数据分析概念,对于多维度数据之间相关性判断一般使用哪种分析模型？,NaN,波士顿矩阵
2,数据分析,多选,2,数据分析概念,使用数学仿真时需要包含哪些元素,A.平均数\nB.分布\nC.方差\nD.可视化图表,A、B、C、D
3,数据分析,判断题,3,数据分析概念,数学仿真可以直接给出业务决策最优解,NaN,错（仿真值只是参考）
4,数据分析,多选,3,数据分析概念,多变量线性回归时确定重要变量的方法包含,A.向前选择\nB.向后选择\nC.混合选择,A、B、C

In [17]:
df.head(10)

,专业,题型,难度,对应知识点,题干,选项（如果有）,答案
0,数据分析,填空题,1,数据分析概念,互联网营销活动数据分析的基本模型是什么,NaN,找出问题→分析问题→解决问题
1,数据分析,填空题,2,数据分析概念,对于多维度数据之间相关性判断一般使用哪种分析模型？,NaN,波士顿矩阵
2,数据分析,多选,2,数据分析概念,使用数学仿真时需要包含哪些元素,A.平均数\nB.分布\nC.方差\nD.可视化图表,A、B、C、D
3,数据分析,判断题,3,数据分析概念,数学仿真可以直接给出业务决策最优解,NaN,错（仿真值只是参考）
4,数据分析,多选,3,数据分析概念,多变量线性回归时确定重要变量的方法包含,A.向前选择\nB.向后选择\nC.混合选择,A、B、C
5,数据分析,判断题,1,数据分析概念,回归中R^2的含义是Y中出现的变化可以被X解释的的比例,NaN,对
6,数据分析,判断题,3,数据分析概念,多变量回归时，F统计量接近于1则一定说明自变量与因变量之间没有关系,NaN,错（还需要参考样本量）
7,数据分析,填空题,3,数据分析概念,在市场营销中，通常对变量进行哪种变化来进行回归分析,NaN,ln函数
8,数据分析,单选,3,数据分析概念,使用ln函数后，以下哪种回归分析可以进行,A.商品排名→商品销量\nB.评价数量→商品销量\nC.评价等级→商品销量,NaN
9,数据分析,判断题,1,数据分析概念,线性回归中t统计量可以用于计算自变量与因变量之间是否存在关系,NaN,对

In [18]:
df["题型"].head()

0    填空题
1    填空题
2     多选
3    判断题
4     多选
Name: 题型, dtype: object

In [19]:
df[["题型","题干"]].head()

    题型                         题干
0  填空题        互联网营销活动数据分析的基本模型是什么
1  填空题  对于多维度数据之间相关性判断一般使用哪种分析模型？
2   多选            使用数学仿真时需要包含哪些元素
3  判断题          数学仿真可以直接给出业务决策最优解
4   多选        多变量线性回归时确定重要变量的方法包含

In [20]:
type(df["题型"])

pandas.core.series.Series

In [21]:
# 选择哪些行有信息
df2[[True,False,True]]

     aa  bbb
101   1    4
103   3    6

In [22]:
df[df["难度"]==2].head()

,专业,题型,难度,对应知识点,题干,选项（如果有）,答案
1,数据分析,填空题,2,数据分析概念,对于多维度数据之间相关性判断一般使用哪种分析模型？,NaN,波士顿矩阵
2,数据分析,多选,2,数据分析概念,使用数学仿真时需要包含哪些元素,A.平均数\nB.分布\nC.方差\nD.可视化图表,A、B、C、D
10,数据分析,填空题,2,数据分析概念,不能直接用线性回归来预测用户购买概率的原因为,NaN,线性回归会使概率值大于1
15,数据分析,填空题,2,数据分析概念,漏斗图在电商业务中最常用的分析场景是,NaN,广告投放分析
17,数据分析,多选题,2,数据分析概念,市场分析领域对于市场的划分包含以下哪些概念,A.头部市场\nB.腰部市场\nC.长尾市场,NaN

## 数据访问

In [23]:
df.loc[[1,5,10]]

      专业   题型  难度   对应知识点                           题干 选项（如果有）            答案
1   数据分析  填空题   2  数据分析概念    对于多维度数据之间相关性判断一般使用哪种分析模型？     NaN         波士顿矩阵
5   数据分析  判断题   1  数据分析概念  回归中R^2的含义是Y中出现的变化可以被X解释的的比例     NaN             对
10  数据分析  填空题   2  数据分析概念       不能直接用线性回归来预测用户购买概率的原因为     NaN  线性回归会使概率值大于1

In [24]:
df.loc[[1,5,10],["题干","题型"]]

                             题干   题型
1     对于多维度数据之间相关性判断一般使用哪种分析模型？  填空题
5   回归中R^2的含义是Y中出现的变化可以被X解释的的比例  判断题
10       不能直接用线性回归来预测用户购买概率的原因为  填空题

In [25]:
df.loc[[1,5,10],"对应知识点":]

     对应知识点                           题干 选项（如果有）            答案
1   数据分析概念    对于多维度数据之间相关性判断一般使用哪种分析模型？     NaN         波士顿矩阵
5   数据分析概念  回归中R^2的含义是Y中出现的变化可以被X解释的的比例     NaN             对
10  数据分析概念       不能直接用线性回归来预测用户购买概率的原因为     NaN  线性回归会使概率值大于1

In [26]:
df.iloc[[0,1,2,3],[0,3,2]]

     专业   对应知识点  难度
0  数据分析  数据分析概念   1
1  数据分析  数据分析概念   2
2  数据分析  数据分析概念   2
3  数据分析  数据分析概念   3

In [27]:
df.iloc[[0,1,3,2]]

,专业,题型,难度,对应知识点,题干,选项（如果有）,答案
0,数据分析,填空题,1,数据分析概念,互联网营销活动数据分析的基本模型是什么,NaN,找出问题→分析问题→解决问题
1,数据分析,填空题,2,数据分析概念,对于多维度数据之间相关性判断一般使用哪种分析模型？,NaN,波士顿矩阵
3,数据分析,判断题,3,数据分析概念,数学仿真可以直接给出业务决策最优解,NaN,错（仿真值只是参考）
2,数据分析,多选,2,数据分析概念,使用数学仿真时需要包含哪些元素,A.平均数\nB.分布\nC.方差\nD.可视化图表,A、B、C、D

In [28]:
df.iloc[[0,1,2,3],1:3]

    题型  难度
0  填空题   1
1  填空题   2
2   多选   2
3  判断题   3

In [29]:
df.iloc[3:,[0,3,2]].head()

     专业   对应知识点  难度
3  数据分析  数据分析概念   3
4  数据分析  数据分析概念   3
5  数据分析  数据分析概念   1
6  数据分析  数据分析概念   3
7  数据分析  数据分析概念   3

In [30]:
df.iloc[0:7,1:3]

    题型  难度
0  填空题   1
1  填空题   2
2   多选   2
3  判断题   3
4   多选   3
5  判断题   1
6  判断题   3

In [31]:
df["专业"][3]

'数据分析'

In [32]:
df[["专业","题干"]][3:6]

     专业                           题干
3  数据分析            数学仿真可以直接给出业务决策最优解
4  数据分析          多变量线性回归时确定重要变量的方法包含
5  数据分析  回归中R^2的含义是Y中出现的变化可以被X解释的的比例

In [33]:
df.at[1,"题干"]

'对于多维度数据之间相关性判断一般使用哪种分析模型？'

In [34]:
df.loc[1,"题干"]

'对于多维度数据之间相关性判断一般使用哪种分析模型？'

In [35]:
df.iat[1,4]

'对于多维度数据之间相关性判断一般使用哪种分析模型？'

In [36]:
df.head()

,专业,题型,难度,对应知识点,题干,选项（如果有）,答案
0,数据分析,填空题,1,数据分析概念,互联网营销活动数据分析的基本模型是什么,NaN,找出问题→分析问题→解决问题
1,数据分析,填空题,2,数据分析概念,对于多维度数据之间相关性判断一般使用哪种分析模型？,NaN,波士顿矩阵
2,数据分析,多选,2,数据分析概念,使用数学仿真时需要包含哪些元素,A.平均数\nB.分布\nC.方差\nD.可视化图表,A、B、C、D
3,数据分析,判断题,3,数据分析概念,数学仿真可以直接给出业务决策最优解,NaN,错（仿真值只是参考）
4,数据分析,多选,3,数据分析概念,多变量线性回归时确定重要变量的方法包含,A.向前选择\nB.向后选择\nC.混合选择,A、B、C

## 表信息的处理

In [37]:
df3 = pd.read_excel("数据分析测试题.xlsx",sheet_name = "第一阶段第三套")

In [39]:
final = pd.concat([df,df3])
final

,专业,题型,难度,对应知识点,题干,选项（如果有）,答案
0,数据分析,填空题,1,数据分析概念,互联网营销活动数据分析的基本模型是什么,NaN,找出问题→分析问题→解决问题
1,数据分析,填空题,2,数据分析概念,对于多维度数据之间相关性判断一般使用哪种分析模型？,NaN,波士顿矩阵
2,数据分析,多选,2,数据分析概念,使用数学仿真时需要包含哪些元素,A.平均数\nB.分布\nC.方差\nD.可视化图表,A、B、C、D
3,数据分析,判断题,3,数据分析概念,数学仿真可以直接给出业务决策最优解,NaN,错（仿真值只是参考）
4,数据分析,多选,3,数据分析概念,多变量线性回归时确定重要变量的方法包含,A.向前选择\nB.向后选择\nC.混合选择,A、B、C
...,...,...,...,...,...,...,...
45,数据分析,单选题,1,NumPy数据运算,Series数据类型声明时，我们想要自定义其索引的值，可以对哪个参数进行设置？,A.indexes\nB.s\nC.index\nD.card,C
46,数据分析,单选题,1,NumPy数据运算,Pandas用什么来标记缺失数据？,"A.NaN\nB.Null\nC. """"\nD. 0",A
47,数据分析,单选题,1,NumPy数据运算,在使用NumPy进行数据运算时，我们可以使用什么函数来直接计算元素的算数平方根,A.root\nB.square\nC.sqrt\nD.subduplicate,C
48,数据分析,单选题,1,NumPy数据运算,有NumPy对象arr，想要计算arr中各元素的4次方，下列代码正确的是？,"A.even(arr,4)\nB.sqrt(arr,4)\nC.power(arr,4)\n...",C
49,数据分析,单选题,1,NumPy数据运算,有NumPy对象arr，想要计算arr中各元素以2为底的对数，下列代码正确的是？,A.np.log(arr)\nB.np.log2(arr)\nC.np.logarithm(...,B

In [43]:
final.count()

专业         100
题型         100
难度         100
对应知识点      100
题干         100
选项（如果有）     47
答案          97
dtype: int64

In [44]:
final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 0 to 49
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   专业       100 non-null    object
 1   题型       100 non-null    object
 2   难度       100 non-null    int64
 3   对应知识点    100 non-null    object
 4   题干       100 non-null    object
 5   选项（如果有）  47 non-null     object
 6   答案       97 non-null     object
dtypes: int64(1), object(6)
memory usage: 6.2+ KB

## 写入文件

In [46]:
final.to_excel("final_data.xlsx", sheet_name = "第一阶段三套题")

In [47]:
# !pip install openpyxl

## 更新数据

In [50]:
df4 = pd.DataFrame({
    "姓名":["建国","爱国","卫国","嘎子"],
    "年龄":[12,14,15,32]
})
df4

   姓名  年龄
0  建国  12
1  爱国  14
2  卫国  15
3  嘎子  32

In [52]:
df4.loc[4] = ["aaa",11]
df4

    姓名  年龄
0   建国  12
1   爱国  14
2   卫国  15
3   嘎子  32
4  aaa  11

In [55]:
df4["是否入党"] = ["是","否","是","是","否"]
df4

    姓名  年龄 是否入党
0   建国  12    是
1   爱国  14    否
2   卫国  15    是
3   嘎子  32    是
4  aaa  11    否

In [57]:
df4["年龄"] = [24,34,53,64,25]
df4

    姓名  年龄 是否入党
0   建国  24    是
1   爱国  34    否
2   卫国  53    是
3   嘎子  64    是
4  aaa  25    否

In [65]:
ddf = df4.drop(0)
ddf
# 删除行操作，drop支持的行索引删除
# drop删除并不作用在原数据上

    姓名  年龄 是否入党
1   爱国  34    否
2   卫国  53    是
3   嘎子  64    是
4  aaa  25    否

In [66]:
df4

    姓名  年龄 是否入党
0   建国  24    是
1   爱国  34    否
2   卫国  53    是
3   嘎子  64    是
4  aaa  25    否

In [67]:
# drop删除，并作用在原数据上
ddf.drop(2,inplace = True)
ddf

    姓名  年龄 是否入党
1   爱国  34    否
3   嘎子  64    是
4  aaa  25    否

In [72]:
# 删除列
df4.drop(["年龄"],axis = 1)

    姓名 是否入党
0   建国    是
1   爱国    否
2   卫国    是
3   嘎子    是
4  aaa    否

In [70]:
df4

    姓名  年龄 是否入党
0   建国  24    是
1   爱国  34    否
2   卫国  53    是
3   嘎子  64    是
4  aaa  25    否

In [73]:
df4.drop(["年龄"],axis = 1,inplace = True)
df4

    姓名 是否入党
0   建国    是
1   爱国    否
2   卫国    是
3   嘎子    是
4  aaa    否